.PHONY: clean All

All:
	@echo "----------Building project:[ JuceVLC - Debug ]----------"
	@cd "JuceVLC" && $(MAKE) -f  "JuceVLC.mk"
clean:
	@echo "----------Cleaning project:[ JuceVLC - Debug ]----------"
	@cd "JuceVLC" && $(MAKE) -f  "JuceVLC.mk" clean
